/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminStdView.java
 *
 * Created on Jan 17, 2011, 9:35:21 PM
 */

package SFUI.Panals;

import SFBasic.Email;
import SFEngine.Mediator;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class SendMail extends javax.swing.JPanel {
    
    private Mediator mediator;

    /** Creates new form AdminStdView */
    public SendMail() {
        initComponents();
        this.mediator = new Mediator();
//        this.debuggerData();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanelcomposemail = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldfrom = new javax.swing.JTextField();
        jTextFieldto = new javax.swing.JTextField();
        jTextFieldcc = new javax.swing.JTextField();
        jTextFieldbcc = new javax.swing.JTextField();
        jTextFieldsubject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreamessage = new javax.swing.JTextArea();
        jButtonsendmail = new javax.swing.JButton();
        jButtonclear = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Compose"));

        jLabel10.setFont(new java.awt.Font("Papyrus", 1, 24));
        jLabel10.setText("Send Mail");

        jLabel1.setText("From:");

        jLabel2.setText("To:");

        jLabel3.setText("Cc:");

        jLabel4.setText("Bcc:");

        jLabel5.setText("Subject:");

        jTextFieldto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtoActionPerformed(evt);
            }
        });

        jTextFieldbcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldbccActionPerformed(evt);
            }
        });

        jTextAreamessage.setColumns(20);
        jTextAreamessage.setRows(5);
        jScrollPane1.setViewportView(jTextAreamessage);

        javax.swing.GroupLayout jPanelcomposemailLayout = new javax.swing.GroupLayout(jPanelcomposemail);
        jPanelcomposemail.setLayout(jPanelcomposemailLayout);
        jPanelcomposemailLayout.setHorizontalGroup(
            jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcomposemailLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldfrom, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(jTextFieldto, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(jTextFieldcc, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(jTextFieldbcc, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(jTextFieldsubject, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                .addGap(131, 131, 131))
            .addGroup(jPanelcomposemailLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanelcomposemailLayout.setVerticalGroup(
            jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcomposemailLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldbcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldsubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButtonsendmail.setText("Send");
        jButtonsendmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonsendmail.setFocusable(false);
        jButtonsendmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsendmailActionPerformed(evt);
            }
        });

        jButtonclear.setText("Clear");
        jButtonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelcomposemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButtonclear, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 407, Short.MAX_VALUE)
                        .addComponent(jButtonsendmail, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelcomposemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonsendmail)
                    .addComponent(jButtonclear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Compose");
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonsendmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsendmailActionPerformed
         this.composeMail();
    }//GEN-LAST:event_jButtonsendmailActionPerformed

    private void composeMail(){
        
        String from = "None";
        String to = "None";
        String cc = "None";
        String bcc = "None";
        String msg = "None";
        
        if(this.validateMail(this.jTextFieldfrom.getText())){
            from = this.jTextFieldfrom.getText();
        }else{
            JOptionPane.showMessageDialog(null,"Incorrect Email Address in the From Field");
            this.clearAll();
            return;
        }
        
        if(this.validateMail(this.jTextFieldto.getText())){
            to = this.jTextFieldto.getText();
        }else{
            JOptionPane.showMessageDialog(null,"Incorrect Email Address in the To Field");
            this.clearAll();
            return;
        }
        
//        if(this.validateMail(this.jTextFieldcc.getText())){
            cc = this.jTextFieldcc.getText();
//        }else{
//            JOptionPane.showMessageDialog(null,"Incorrect Email Address in the Cc Field");
//        }
//        
//        if(this.validateMail(this.jTextFieldbcc.getText())){
            bcc = this.jTextFieldbcc.getText();
//        }else{
//            JOptionPane.showMessageDialog(null,"Incorrect Email Address in the BCc Field");
//        }
        
        if(jTextAreamessage.getText()!=(null)){
            msg = this.jTextAreamessage.getText();
        }else{
            JOptionPane.showMessageDialog(null,"Message Body is Empty");
            return;
        }
        
        Email currentMail = new Email(to, from, bcc, cc, msg);
        
        if(this.mediator.sendMail(currentMail)){
            this.clearAll();
        }else{
            JOptionPane.showMessageDialog(null, "Couldn't send the mail. Please check the database connectivity.", "Spam Filter Confirmation", JOptionPane.WARNING_MESSAGE);
        }    
        
        
    }
    
    private boolean validateMail(String emailAddress){
        Pattern rfc2822 = Pattern.compile(
                "^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$"
        );

        if (rfc2822.matcher(emailAddress).matches()) {
            return true;
        }else{
            return false;
        }
    }
    
    private void jTextFieldbccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldbccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldbccActionPerformed

    private void jTextFieldtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtoActionPerformed

    private void jButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclearActionPerformed
        this.clearAll();
    }//GEN-LAST:event_jButtonclearActionPerformed

    private void clearAll(){
        this.jTextFieldto.setText("");
        this.jTextFieldfrom.setText("");
        this.jTextFieldcc.setText("");
        this.jTextFieldbcc.setText("");
        this.jTextFieldsubject.setText("");
        this.jTextAreamessage.setText("");
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonclear;
    private javax.swing.JButton jButtonsendmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelcomposemail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreamessage;
    private javax.swing.JTextField jTextFieldbcc;
    private javax.swing.JTextField jTextFieldcc;
    private javax.swing.JTextField jTextFieldfrom;
    private javax.swing.JTextField jTextFieldsubject;
    private javax.swing.JTextField jTextFieldto;
    // End of variables declaration//GEN-END:variables

}
